### ISSUE TITLE
Unable to run `gmi init` - 'Namespace' object has no attribute 'verbose'

### ISSUE THREAD

**Issue by pioto** [gauteh/lieer#250]
Just tried setting up from the `master` branch, and I get this error:

```
Traceback (most recent call last):        
  File "/home/pioto/.local/bin/gmi", line 24, in <module>                                   
    g.main ()                                                                               
  File "/home/pioto/.local/lib/python3.11/site-packages/lieer/gmailieer.py", line 236, in main                                                                                           
    args.func (args)                                                                        
  File "/home/pioto/.local/lib/python3.11/site-packages/lieer/gmailieer.py", line 239, in initialize                                                                                     
    self.setup (args, False)                                                                
  File "/home/pioto/.local/lib/python3.11/site-packages/lieer/gmailieer.py", line 281, in setup                                                                                          
    self.verbose          = args.verbose                                                                                                                                                 
                            ^^^^^^^^^^^^                                                                                                                                                 
AttributeError: 'Namespace' object has no attribute 'verbose'                   
```

I checked out v1.4 instead and don't have any issue, so I assume this is a recent regression, probably from https://github.com/gauteh/lieer/pull/245 ?

**Comment by gauteh** [comment]
Fixed in #252.
